language: c
dist: trusty
cache:
  directories:
    - $HOME/bin
    - $HOME/lib
install:
  - PATH="$HOME/bin:$PATH"
  - LD_LIBRARY_PATH="$HOME/lib:${LD_LIBRARY_PATH}"
  - export PATH LD_LIBRARY_PATH
  - gpg2 || ./build-gpg.sh
script:
  - gpg2 --version
