language: c
dist: trusty
cache:
  directories:
    - $HOME/bin
    - $HOME/lib
env: GPG_VERSION='2.1.18'
notifications:
  email: false
install:
  - PATH="$HOME/bin:$PATH"
  - LD_LIBRARY_PATH="$HOME/lib:${LD_LIBRARY_PATH}"
  - export PATH LD_LIBRARY_PATH
  - gpg2 --version | grep "gpg (GnuPG) $GPG_VERSION" || ./build-gpg.sh
script:
  - gpg2 --version | grep "gpg (GnuPG) $GPG_VERSION"
